from django.db import models

# Create your models here.

class employee_tb(models.Model):
    fname = models.CharField(max_length=200,null='empty')
    lname = models.CharField(max_length=200,null='empty')
    email = models.CharField(max_length=200,null='empty')
    phone = models.CharField(max_length=200,null='empty')
    dob = models.CharField(max_length=200,null='empty')
    age = models.CharField(max_length=200,null='empty')
    gender = models.CharField(max_length=200,null='empty')
    marital_status = models.CharField(max_length=200,null='empty')
    address = models.TextField(null='empty')
    language = models.TextField(null='empty')
    qalification = models.TextField(null='empty')
    experience = models.TextField(null='empty')
    jobopted = models.TextField(null='empty')
    compknowledge = models.TextField(null='empty')
    resume = models.FileField(upload_to='employe_resume',null='empty')



class employer_tb(models.Model):
    logo = models.ImageField(upload_to='employer_logo',null='empty')
    nameorg = models.TextField(null='empty')
    rname = models.CharField(max_length=200,null='empty')
    email = models.CharField(max_length=200,null='empty')
    phone = models.CharField(max_length=200,null='empty')
    phoner = models.CharField(max_length=200,null='empty')
    designation = models.TextField(null='empty')
    address = models.TextField(null='empty')
    website = models.URLField(max_length=500,null='empty')
    positionnumber =  models.CharField(max_length=200,null='empty')
    gender = models.CharField(max_length=200,null='empty')
    jobtitle = models.CharField(max_length=500,null='empty')
    description = models.TextField(null='empty')
    positionnumber1 =  models.CharField(max_length=200,null='empty')
    gender1 = models.CharField(max_length=200,null='empty')
    jobtitle1 = models.CharField(max_length=500,null='empty')
    description1 = models.TextField(null='empty')
    positionnumber2 =  models.CharField(max_length=200,null='empty')
    gender2 = models.CharField(max_length=200,null='empty')
    jobtitle2 = models.CharField(max_length=500,null='empty')
    description2 = models.TextField(null='empty')
    positionnumber3 =  models.CharField(max_length=200,null='empty')
    gender3 = models.CharField(max_length=200,null='empty')
    jobtitle3 = models.CharField(max_length=500,null='empty')
    description3 = models.TextField(null='empty')
    positionnumber4 =  models.CharField(max_length=200,null='empty')
    gender4 = models.CharField(max_length=200,null='empty')
    jobtitle4 = models.CharField(max_length=500,null='empty')
    description4 = models.TextField(null='empty')
    # positionnumber5 =  models.CharField(max_length=200,null='empty')
    # gender5 = models.CharField(max_length=200,null='empty')
    # jobtitle5 = models.CharField(max_length=500,null='empty')
    # description5 = models.TextField(null='empty')
    # positionnumber6 =  models.CharField(max_length=200,null='empty')
    # gender6 = models.CharField(max_length=200,null='empty')
    # jobtitle6 = models.CharField(max_length=500,null='empty')
    # description6 = models.TextField(null='empty')
    # positionnumber7 =  models.CharField(max_length=200,null='empty')
    # gender7 = models.CharField(max_length=200,null='empty')
    # jobtitle7 = models.CharField(max_length=500,null='empty')
    # description7 = models.TextField(null='empty')
    # positionnumber8 =  models.CharField(max_length=200,null='empty')
    # gender8 = models.CharField(max_length=200,null='empty')
    # jobtitle8 = models.CharField(max_length=500,null='empty')
    # description8 = models.TextField(null='empty')
    # positionnumber9 =  models.CharField(max_length=200,null='empty')
    # gender9 = models.CharField(max_length=200,null='empty')
    # jobtitle9 = models.CharField(max_length=500,null='empty')
    # description9 = models.TextField(null='empty')
    # positionnumber10 =  models.CharField(max_length=200,null='empty')
    # gender10 = models.CharField(max_length=200,null='empty')
    # jobtitle10 = models.CharField(max_length=500,null='empty')
    # description10 = models.TextField(null='empty')
    

class admin_tb(models.Model):
    name = models.CharField(max_length=200,null='empty')
    email = models.CharField(max_length=200,null='empty')
    password = models.TextField(null='empty')
    pwd = models.TextField(null='empty')


